insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','CROSSVILLE-AVAILABILITY','crossville-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="crossville-availability"><from uri="properties:{{dana.crossville.availability.start}}"/><to uri="properties:{{dana.crossville.availability.end}}"/></route></routes>');
insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','LC-AVAILABILITY','lc-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="lc-availability"><from uri="properties:{{dana.lc.availability.start}}"/><to uri="properties:{{dana.lc.availability.end}}"/></route></routes>');
insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','HENDERSON-AVAILABILITY','henderson-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="henderson-availability"><from uri="properties:{{dana.henderson.availability.start}}"/><to uri="properties:{{dana.henderson.availability.end}}"/></route></routes>');
insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','ALBION-AVAILABILITY','albion-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="albion-availability"><from uri="properties:{{dana.albion.availability.start}}"/><to uri="properties:{{dana.albion.availability.end}}"/></route></routes>');
insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','LIMA-AVAILABILITY','lima-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="lima-availability"><from uri="properties:{{dana.lima.availability.start}}"/><to uri="properties:{{dana.lima.availability.end}}"/></route></routes>');

insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','application.name','pzv-integration-platform');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.crossville.availability.start','direct:crossville-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.crossville.availability.end','mock:crossville-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.lc.availability.start','direct:lc-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.lc.availability.end','mock:lc-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.henderson.availability.start','direct:henderson-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.henderson.availability.end','mock:henderson-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.albion.availability.start','direct:albion-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.albion.availability.end','mock:albion-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.lima.availability.start','direct:lima-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.lima.availability.end','mock:lima-availability');