insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','CROSSVILLE-AVAILABILITY','crossville-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="crossville-availability"><from uri="timer://{{dana.crossville.availability.start}}?fixedRate=true&amp;period=5000" /><bean ref="samplebean" method="ping()"/><log message="Body ==> ${body}"/><to uri="{{dana.crossville.availability.end}}" /></route></routes>');
insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','LC-AVAILABILITY','lc-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="lc-availability"><from uri="{{dana.lc.availability.start}}" /><to uri="{{dana.lc.availability.end}}" /></route></routes>');
insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','HENDERSON-AVAILABILITY','henderson-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="henderson-availability"><from uri="{{dana.henderson.availability.start}}" /><to uri="{{dana.henderson.availability.end}}" /></route></routes>');
insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','ALBION-AVAILABILITY','albion-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="albion-availability"><from uri="{{dana.albion.availability.start}}" /><to uri="{{dana.albion.availability.end}}" /></route></routes>');
insert into route (tenantid,featureid,routeid,active,routexml) values ('DANA-US','LIMA-AVAILABILITY','lima-availability',1,'<routes xmlns="http://camel.apache.org/schema/spring"><route id="lima-availability"><from uri="{{dana.lima.availability.start}}" /><to uri="{{dana.lima.availability.end}}" /></route></routes>');

insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','application.name','pzv-integration-platform');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.crossville.availability.start','crossville-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.crossville.availability.end','mock:crossville-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.lc.availability.start','direct:lc-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.lc.availability.end','mock:lc-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.henderson.availability.start','direct:henderson-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.henderson.availability.end','mock:henderson-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.albion.availability.start','direct:albion-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.albion.availability.end','mock:albion-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.lima.availability.start','direct:lima-availability');
insert into pz_platformservice_integration(appname,configkey,configvalue) values ('pzv-integration','dana.lima.availability.end','mock:lima-availability');